version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:Obrigada@docker.for.mac.localhost:3306/my_restaurant
